Version 0.2.1 - hosting help scripts Add nginx configuration Add LetsEncrypt certificate guide Add database buildings data initialization with sql file generated Fix buildings insertion (process multipolygons) Add /api/ prefix to swagger to work with nginx proxy

diff --git a/backend/Dockerfile b/backend/Dockerfile
--- a/backend/Dockerfile
+++ b/backend/Dockerfile
@@ -1,11 +1,21 @@
-FROM python:3.10-alpine
+FROM python:3.10-slim
 
-RUN apt update && apt install fonts-liberation
+RUN apt update && \
+    apt install -y fonts-liberation libpq-dev python3-dev build-essential && \
+    pip install psycopg2 && \
+    apt purge -y python3-dev build-essential --autoremove
 
 COPY requirements.txt /
-RUN python3 -m pip install --no-cache-dir -r requirements.txt
 
+RUN python3 -m pip install --no-cache-dir -r requirements.txt
 
 COPY facades_api/ /facades_api/
 
-ENTRYPOINT [ "python3", "-m", "facades_api" ]
+RUN echo "cd facades_api/db" > /entrypoint.sh && \
+    echo "alembic upgrade head" >> /entrypoint.sh && \
+    echo "if [ $? = 0 ]; then echo 'Database schema syncronized'; else echo 'alembic upgrade has failed, database state is not determined'; exit 1; fi" >> /entrypoint.sh && \
+    echo "cd /" >> /entrypoint.sh && \
+    echo "python3 -m facades_api" >> /entrypoint.sh
+
+ENTRYPOINT ["/bin/sh"]
+CMD ["/entrypoint.sh"]
